MinimumStatiqWebVersion-CleanBlog: "1.0.0-beta.36"
SiteTitle: "Stefano Locatelli's Blog"
SiteDescription: "Thoughts and experiences on Azure, AI and Microsoft 365 Development"
PageTitle: |
  =>
  {
    string siteTitle = Context.GetString("SiteTitle");
    string title = GetString("Title");
    return string.IsNullOrWhiteSpace(siteTitle) ? title : (string.IsNullOrWhiteSpace(title) ? siteTitle : $"{siteTitle} - {title}");
  }
Copyright: => $""
PostSources: posts/**/*
IsPost: => Context.Outputs.FilterSources(Context.GetString("PostSources")).ContainsById(Document)
PageSources: pages/**/*
IsPage: => Context.Outputs.FilterSources(Context.GetString("PageSources")).ContainsById(Document)
Layout: /_layout.cshtml

# Hosting settings
Host: blog.stlocate.net
LinksUseHttps: true

GenerateSearchIndex: true